---
title: "Geocoding Zip Codes"
author: "Dylan Koproski"
date: "2023-11-21"
output: html_document
---

```{r, echo = FALSE}
library(tidyverse)
library(zipcodeR)
library(leaflet)
```

# Geocoding tidied data

Leaflet requires latitudes and longitudes for mapping, we can use the `geocode_zip()` function:

```{r}
air_quality_geocoded =
  read_csv("cleaned_data/air_quality_zips.csv") 

geocoded_data =
  geocode_zip(unique(air_quality_geocoded$zip))

#One zip code returned NA, manual replacement of missing data from zip code 11695, lat, long = 40.5600, 73.8900. Note this zip code likely returned NA since it is a very small area (I believe it represents a park).
  
geocode_df =
  geocoded_data |> 
  mutate(lat = ifelse(zipcode == 11695, 40.5600, lat),
         lng = ifelse(zipcode == 11695, -73.8900, lng)) |> 
  mutate(zipcode = as.character(zipcode))
  
```

## Merging geocoded zip codes to dataframe

```{r}
air_quality_geocoded_df =
  air_quality_geocoded |> 
  mutate(zip = as.character(zip)) |>  
  left_join(geocoded_data, by = c("zip" = "zipcode"))
```

